import Head from 'next/head'
import { useMetamask } from '../store/metamask'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { address, network, requestConnect } = useMetamask()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome
        </h1>

        {address? (<p className={styles.description}>
          Wallet address{' '}
          <code className={styles.code}>{address}</code>
        </p>) : (
          <button onClick={requestConnect} className="button">Connect Metamask</button>
        )
}

        <div className={styles.grid}>
            <h2>Network</h2>
            <p>Name: {network.name && network.name.toUpperCase()}</p>
            <p>ChainID: {network.chainId}</p>
        </div>
      </main>
    </div>
  )
}
